### ISSUE TITLE
Virtual keyboard for entering server names with VR controller?

### ISSUE THREAD

**Issue by BenMcLean** [DrBeef/QuakeGVR#12]
It would be really nice if I could enter a server name using the VR controller without needing to pack a Bluetooth keyboard to play on my private server.

**Comment by DrBeef** [comment]
I'm afraid implementing a full virtual keyboard would be well beyond what I am able to do. However there is a work-around. If you look at the instructions posted here:

https://www.reddit.com/r/quakegearvr/comments/3j9zak/usabased_multiplayer_server_up_and_running_full/

You can actually supply server names in the commandline.txt file. I presume that still works, I must admit I've not actually tried it in this new version!
