### ISSUE TITLE
Add options to increase internal resolution (Super Sampling)

### ISSUE THREAD

**Issue by TrackBallPower** [DrBeef/QuakeGVR#13]
Apparently QuakeGVR clarity can be massively improved if it were possible to increase internal resolution (Super Sampling) to 1.5 for example. 
Is it maybe possible to add some options that allows one to select from a few different internal resolutions (Super Sampling)?

See also this reddit post:
https://www.reddit.com/r/quakegearvr/comments/9rm4wm/eyecandy_guide_on_how_to_increase_internal/

**Comment by DrBeef** [comment]
Working on this.. should get something out very soon. It needs to be set through a command line parameter as it has to be configured prior to creation of the framebuffers. I'll ensure an example commandline.txt is included so anyone who wants to use supersampling just has to tweak it.

**Comment by TrackBallPower** [comment]
That sounds like a decent solution. 
Just wondering: could that same commandline.txt then also be used to load a specific mod at startup for example?

**Comment by DrBeef** [comment]
That may be something darkplaces engine already provides support for.. I'll have a look

**Comment by DrBeef** [comment]
you could try adding:

-game dpmod

to commandline.txt and see if that works (assuming you are interested in getting dpmod to load by default.. should work with any other mod too), I've not been able to try it myself yet.

**Comment by TrackBallPower** [comment]
Ok, i created a file called commandline.txt in the QGVR folder with the line that you suggested and started Quake GVR, but it didn't load the dpmod unfortunately.

**Comment by DrBeef** [comment]
Closing this issue as I just released v.1.3.0 which contains the ability to use supersampling
