### ISSUE TITLE
Request - combined locomotion 3dof and gamepad

### ISSUE THREAD

**Issue by neitey** [DrBeef/QuakeGVR#15]
Suggest adding a new locomotion style. Using the Gear VR controller to only control the aiming and allow to use the thumbstick of a Bluetooth gamepad to control direction of movement in relation to viewing direction.

Up till now none of the available modes allow this. Gamepad input and gear controller always influence each other.

**Comment by DrBeef** [comment]
This is now fixed in v1.3.1
