### ISSUE TITLE
Request - crosshair option when playing non 3DOF

### ISSUE THREAD

**Issue by neitey** [DrBeef/QuakeGVR#17]
Request  - would love to see the crosshair option to return like in previous versions. torchlight and laserbeam work great with the 3DOF controller but I would prefere to play it with the vanilla crosshair when using a gamepad. Easier to aim in fast Multiplayer. Torchlight makes me a little uneasy after a while. maybe of the constant changing of its size, depending on the surfaces distance it bounces of.

**Comment by DrBeef** [comment]
I think you might be able to reinstate it using a config.cfg setting:

"crosshair" "1"

**Comment by neitey** [comment]
Will try and report back

**Comment by neitey** [comment]
Thanks, close issue
