### ISSUE TITLE
Gamepad bug/issue

### ISSUE THREAD

**Issue by neitey** [DrBeef/QuakeGVR#18]
Tested wit two different Gamepads. Problem can be reproduced. Occurring everytime and always through the game.

When the player comes to a full stop after walking/running forward, the player makes a slight step to the side before coming to a full stop. Could induce motion sickness.

Reproduced with two different gamepads, different models, but same manufacturer (ipega).

**Comment by neitey** [comment]
Seems to have vanished with the latest update (1.3.1)

**Comment by DrBeef** [comment]
Good stuff!, I wondered if it might with the way the gamepad direction now works in conjunction with the headset orientation (rather than the 3DoF controller orientation).
