### ISSUE TITLE
Request: compiled ArCore apk

### ISSUE THREAD

**Issue by schweini** [DrBeef/QuakeGVR#22]
Could we have a pre-compiled apk (especially one that uses ArCore?

**Comment by DrBeef** [comment]
Not sure what you mean?, the releases tab has the precompiled apk, latest version v1.3.1

You need to install ArCore separately if you want to use the positional tracking.

**Comment by schweini** [comment]
Sorry - my bad! I somehow forgot to check 'releases'!
