### ISSUE TITLE
Gamepad mode broken in verion 1.3.1

### ISSUE THREAD

**Issue by neitey** [DrBeef/QuakeGVR#23]
Gamepad only mode is unusable after update. 
Happens if: 3DOF diasbled, swievelchair mode activate.

Gamepad mode ia not fixed to hmd orientation. 

I think this needs fixing, most people only have a gamepad. They try QGVR, get frustrated real quick. Never come back.

**Comment by DrBeef** [comment]
Fixed (on my lunch break) in v1.3.2

**Comment by neitey** [comment]
Amazing thank you. When my money comes i will make sure you have a lunch on
me.

Am Do., 15. Nov. 2018, 14:41 hat Simon <notifications@github.com>
geschrieben:
