### ISSUE TITLE
[Solved for next release] This command makes QGVR run butter smooth

### ISSUE THREAD

**Issue by neitey** [DrBeef/QuakeGVR#26]
I'll make it short.

"sys_ticrate" "0.0166667"

this is the only thing that Dpmod does different! Add this to the next Update and there is no need for Dpmod any more.
Put this line in your config.cfg in /id1 folder and it will run smooth as butter.It took a few evenings to read trough a lot of old Quake wikis. But in the end the solution was very easy.

**Comment by TrackBallPower** [comment]
And yes i can confirm that this solution works like a charm! 
Massive performance improvement i would say, even better performance then with the DPmod enabled.

**Comment by neitey** [comment]
Implemented in new release, issue closed. Thanks to Developer
