### ISSUE TITLE
High  Resolution Textures - How To

### ISSUE THREAD

**Issue by Mizar01** [DrBeef/QuakeGVR#29]
In the official QuakeGVR page is said:

"It is also highly recommended you download the hi-res textures and unpack them to the id1 folder."

Is this valid yet? Where's the 'id1' folder inside the apk?
I tried to put the .pak files in the apk, but during install I get a signature error. I should create sha-256 hashes for the pak files and put it in the manifest (maybe along with a new signature?)

There's some specific instructions on that?

**Comment by DrBeef** [comment]
Hi

The id1 folder isn't in the apk, it is on your phone's memory after the app has installed, you'll find a root folder called QGVR and then an id1 folder in that.
