### ISSUE TITLE
Mouse controls?

### ISSUE THREAD

**Issue by BenMcLean** [DrBeef/QuakeGVR#3]
I'd like to play this using a Bluetooth keyboard and mouse AND headtracking at the same time, so I can use the mouse to turn around quickly, but use my head for more precise aiming. I'd appreciate any help getting this to work.

**Comment by BenMcLean** [comment]
Why was this closed? :(

**Comment by DrBeef** [comment]
Sorry, I should have commented. I'm afraid I'm not going to be adding mouse controls myself.

If someone else looks at it they are welcome to submit a pull request.

Apologies for the abrupt closure of this issue!

**Comment by BenMcLean** [comment]
I tried looking into the source myself (a year ago, so my memory's not real clear) and it looked like you redirected the mouse controls away from the actual mouse to the headtracking instead. But I think just adding the mouse movement vector and head tracking vector together would do the trick if there was a way to just put ordinary mouse controls back.
