### ISSUE TITLE
movement drift

### ISSUE THREAD

**Issue by ManuelGDA** [DrBeef/QuakeGVR#30]
While playing with the xbox wireless gamepad, as soon as you stop pushing the analog sticks for moving/turning, you keep moving turning in that same direction. Its like a micro drift, very small/smooth/minimal. The only way I found to stop it is to carefully recenter the sticks. Its as the sensitivity of the analog stick is too high or doesnt have a centered deadzone to keep still. how can I adjust this? thank you for this awesome gearvr port!

**Comment by neitey** [comment]
Same error here. A deadzone would fix this.

**Comment by Eispfogel** [comment]
Same here - i hope it can be fixed.

**Comment by QUAKEULUS** [comment]
issue confirmed with xbox one s controller.

**Comment by DrBeef** [comment]
I'm dropping a new release shortly, v1.3.4, in which I've added a new cvar:  cl_controllerdeadzone

If the default value isn't enough (it probably isn't), then set it to something higher in the config.cfg file to try to eliminate the drift. Basically it is a value between 0 and 1.

I don't have access to my controller at the moment, so I am going to have to ask if you could test it and let me know how it goes.

**Comment by QUAKEULUS** [comment]
Sure thing, did you happen to fix the keyboard issue as well? it was a little tedious replacing the autoexec.cfg and relaunching the game every time I wanted to try a new command.

**Comment by ManuelGDA** [comment]
As soon as I get the new release I´ll test it, thank you :D!

**Comment by QUAKEULUS** [comment]
tested a few values, cl_controllerdeadzone 0.2 works fine with xbox one s bluetooth controller.
Thanks for the fix.

**Comment by ManuelGDA** [comment]
Tested too. I second what QUAKEULUS said, adding "cl_controllerdeadzone" "0.2"  to config.cfg does the trick ;)

**Comment by neitey** [comment]
Confirmed!
cl_controllerdeadzone" "0.2 does the trick. should be added to new release since it doesn't harm even when not using an Xbox one controller. I think the Issue can be closed :)
