### ISSUE TITLE
Occasional stutter not related to phone performance .

### ISSUE THREAD

**Issue by neitey** [DrBeef/QuakeGVR#32]
QGVR has occasional low fps issues in some game situations. Strangely these framerate drops seem to be unrelated to phone SoC performance. I use the S7 and S8 to run the game and it behaves the same perfomance wise. Even doing massive undersampling (Super Sampling value 0,5) does not have any effect on the framerate drops.

**Comment by neitey** [comment]
Example for everyone to try is the entrance to Episode 2. No matter what phone is used, how strong undersapmling is applied, the game stutters.

**Comment by blaydes99** [comment]
Getting the same issue here. Tested on latest build with Edge S7 and GearVR headset. Positional (head) tracking is turned off to test.
Another area with heavy stuttering is in E1M1 right before the first door after the bridge/water area.

**Comment by neitey** [comment]
Uninstall ARcore for a much better performance. Even when positional
tracking is turned of ingame, ot uses a lot of system resources.

blaydes99 <notifications@github.com> schrieb am Do., 14. März 2019, 20:17:

**Comment by blaydes99** [comment]
> 
> Uninstall ARcore for a much better performance. Even when positional tracking is turned of ingame, ot uses a lot of system resources. blaydes99 <notifications@github.com> schrieb am Do., 14. März 2019, 20:17:

Good to know! The phone had been giving me the "overheating" message after playing for 5 to 10 minutes. I uninstalled ARcore and the overheating problem went away. Framerate feels pretty smooth, except of course in those problem areas (as you mentioned in your original post) where the frames drop to 4-5 fps for some reason.

**Comment by Eispfogel** [comment]
Same on E2M4 - The Ebon Fortress. It is pretty unplayable in those areas.
It seems that the whole map geometry is rendered at once instead of cutting everything away which isn't visible.
Maybe a problem with the BSP tree render algorithm?

**Comment by neitey** [comment]
**Issue successfully located and fixed by user Vlad (only a workaround for now):**
https://github.com/DrBeef/QuakeGVR/issues/35#issue-437599442 

Great work

**Comment by neitey** [comment]
Fixed. 

See other post related to the command "gl_nopartialtextureupdates" "1"
