### ISSUE TITLE
Found the source of the performance bug due to lights in darkplaces and a potential fix.

### ISSUE THREAD

**Issue by QUAKEULUS** [DrBeef/QuakeGVR#35]
Ever since /u/DrBeef_ldn 's awesome initial release of QuakeVR, there was a nauseating performance issue when approaching certain torches or blinking lights. There is a certain cvar "slowmo" that can mitigate that but it makes the entire game slow-down, which is cool in itself, but even at slowmo 0.7 (30% slower game speed) the performance issue is still there.

Some places it's not a big deal, with drops to 35-40 fps, but in some areas, like the easy hub (start game, at entrance go to the left slipgate with EASY, look right at fire under stairs) it can drop to a nauseating 15 fps.

I've tried every cvar in darkplaces to no avail to fix this. Except for slowmo, which makes it unplayable, and r_fullbright 1 which is OK, but taking away all lighting from the game makes the atmosphere a lot less enjoyable.

I considered a macro like 
if $fps < 50 then set slowmo 0.2 else set slowmo 1

but $fps isnt a variable afaik.

**SOLUTION:**

Anyway, not the first to have this performance problem as discussed here:

http://quakeone.com/forum/quake-help/quake-clients/4355-old-darkplaces-vs-fitzquake-aguirre-quake

and

http://celephais.net/board/view_thread.php?id=60306&start=57&end=81

lightstyles is quake's switchable light system, and is described here:

https://quakewiki.org/wiki/lightstyle

Also lightstyle data is stored in the save file and the save file is plaintext so I tried modifying one in a problematic area and replacing all the patterns of all the lightstyles under **// DarkPlaces extended savegame** to just m for normal light level, and the problem completely disappeared. 

Here is a modified savegame for the entrance level that was a problematic performance area:
https://drive.google.com/open?id=1j8I2g1lTFgmXqtosoc04N3OZXQrB_CRR

Sadly, it doesn't work after a new map is loaded, so right now,, you can just make a savefile per map, but a more permanent elegant solution would be preferred

**Comment by neitey** [comment]
Can second this. This fix works and gets rid of the performance issue / stutter.
in combination with the the cvar "sys_ticrate" "0.0166667" (already implemented in the "All in one" download on r/quakegearvr) it is now running a comnstant framerate.

hope these fixes find their way in an new build.

**Comment by QUAKEULUS** [comment]
As pointed out by reddit user emile_b, settings gl_nopartialtextureupdates 1 also fixes the issue while retaining all of the light animations

**Comment by neitey** [comment]
Just tested 3 maps with critical perfromance and I can second this!

**"gl_nopartialtextureupdates" "1"**

The Quad Touch developer (emile_b) found the permanent solution as pointed out on reddit r/quakegearvr. And Quakeulus had the right lead ...

Together with "sys_ticrate" "0.0166667" (eleminates microstutters) added to the config.cfg QGVR there are **almost no performance problems left!**

I you follow the sticky guide on r/quakegearvr, the fixes will already be included.

**Comment by DrBeef** [comment]
Amazing work!

I'll see if I can drop a release with the above changes in as defaults so people don't have to mess about with config files.

**Comment by DrBeef** [comment]
Just released 1.3.3, please re-open this issue if it isn't fixed with the suggested default configuration
