### ISSUE TITLE
SuperQOT VR

### ISSUE THREAD

**Issue by BenMcLean** [DrBeef/QuakeGVR#4]
The SUPERHOT team made [a cool mod for singleplayer Quake a few years ago](https://superhotgame.com/SUPERQOT/). It is very fun to play.

[I put their source code up on Github because GPL](https://github.com/BenMcLean/darkplaces-SUPERQOT). Unfortunately, their code has not been merged into the official DarkPlaces Quake source, so it wasn't inherited by QuakeGVR. Still, it would be neat to see this game in VR by merging the changes to Darkplaces Quake made by QuakeGVR and SuperQOT together into one.

**Comment by DrBeef** [comment]
I won't be looking at this I'm afraid
