### ISSUE TITLE
 Command  "cl_controllerdeadzone" does not stick in config. Gets deleted after restarting Quake

### ISSUE THREAD

**Issue by neitey** [DrBeef/QuakeGVR#40]
cl_controllerdeadzone 0.2 does get deleted after running quake a second time. I does not stick, one has to reenter in before every run.

**Comment by ManuelGDA** [comment]
yes this happens to me too :(  what I did to not depend on the pc to correct it (gear vr) is to keep a backup copy of the config.cfg file in the parent folder and when I want to play/test I copy/paste/replace and voilá! I dont know if you can use a file manager or something similar/workaround on the go but for now, untill fixed, this is a "solution" without the need to connect to a PC

**Comment by DrBeef** [comment]
I believe you can put things into autoexec.cfg and that won't be overwritten, that should solve your problem.

There's some other issue though, as the config.cfg shouldn't be overwritten at all, so something else is going on there that will need fixing in the Quest version when I get to it.
