### ISSUE TITLE
Laser "sight" on weapons ?

### ISSUE THREAD

**Issue by motorsep** [DrBeef/QuakeGVR#5]
When it comes to aiming in VR using 3DoF controller I think having laser beam mounted to each weapon is critical. Any chance you could attach one using code alone ? (I'd add it to each model if there were sane tools to edit those models)

Thanks beforehand

**Comment by DrBeef** [comment]
Several people have requested this, I'm working on it at the moment, so the next release will definitely have this feature.

**Comment by DrBeef** [comment]
Available in v1.2.0
