### ISSUE TITLE
Move in the direction that you are looking

### ISSUE THREAD

**Issue by TrackBallPower** [DrBeef/QuakeGVR#6]
I really need the same movement method as DGVR (Doom for Gear VR), meaning to be able to move by looking in a specific direction.
The swivel chair movement is making me nauseous, most likely because i lose real world orientation.
Other then that, QuakeGVR is a masterpriece, it's incredibly immersive!

**Comment by DrBeef** [comment]
I'll be adding this to the next release

**Comment by TrackBallPower** [comment]
Awesome, thanks!

**Comment by DrBeef** [comment]
Available in v1.2.0
