### ISSUE TITLE
Move in the direction your gun (Gear VR controller) is pointing - Onward style locomotion

### ISSUE THREAD

**Issue by TrackBallPower** [DrBeef/QuakeGVR#8]
I thought i'd bring this up because the onward style of locomotion was so well received and perceived to be very effective at reducing nausea.
So the idea is that when you press forward on the Gear VR controller, you can steer yourself in the right direction by pointing the controller in the direction you want to go to.
I am not sure if it will be a lot of work to implement this as an optional feature that can be enabled in the options menu?

**Comment by DrBeef** [comment]
Isn't this how it works already?, do you mean you want to remove the ability to strafe left and right using the controller? At the moment if you are touching the top edge of the track pad (moving forwards) and you then point it left (keeping your finger in the same location) you will move to the left. I'm not sure what it is you are asking for outside the behaviour already there.

The other issue you raised will be addressed however (being able to move in the direction you are looking)

**Comment by TrackBallPower** [comment]
My apologies, i tend to do everything from the wrist and then there is almost no effect.
I now tried extending my arm fully forward and then point in a specific direction and yes, then it works.
The only thing that i am not able to do is turn in a limited amount of space.
Is there any way to make quick turns, other then using a swivel-chair?
