### ISSUE TITLE
Interesting Strings found in Injector app you link.

### ISSUE THREAD

**Issue by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [DrBeef/QuakeGVR#9]
FYI:

**http://
http://play.google.com/store/apps/
http://play.google.com/store/apps/category/GAME
http://schemas.android.com/apk/res/android
http://www.example.com
http://www.google.com
https://
https://app-measurement.com/a
https://arworks.hu/gzalai/
https://csi.gstatic.com/csi
https://e.crashlytics.com/spi/v2/events
https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js
https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js
https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js
https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html
https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js
https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js
https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html
https://imasdk.googleapis.com/admob/sdkloader/native_video.html
https://pagead2.googlesyndication.com/pagead/gen_204
https://pagead2.googlesyndication.com/pagead/gen_204?id=gmob-apps
https://play.google.com/store/apps/details
https://play.google.com/store/apps/details?id=%1$s&rdid=%1$s&rdot=%2$d
https://plus.google.com/
https://plus.google.com/%s/about
https://settings.crashlytics.com/spi/v2/platforms/android/apps/%s/settings
https://support.google.com/dfp_premium/answer/7160685#push
https://www.google.com
https://www.google.com/dfp/debugSignals
https://www.google.com/dfp/inAppPreview
https://www.google.com/dfp/linkDevice
https://www.google.com/dfp/sendDebugData
https://www.googleapis.com/auth/appstate
https://www.googleapis.com/auth/connections.read
https://www.googleapis.com/auth/datastoremobile
https://www.googleapis.com/auth/display_ads
https://www.googleapis.com/auth/drive
https://www.googleapis.com/auth/drive.appdata
https://www.googleapis.com/auth/drive.apps
https://www.googleapis.com/auth/drive.file
https://www.googleapis.com/auth/fitness.activity.read
https://www.googleapis.com/auth/fitness.activity.write
https://www.googleapis.com/auth/fitness.blood_glucose.read
https://www.googleapis.com/auth/fitness.blood_glucose.write
https://www.googleapis.com/auth/fitness.blood_pressure.read
https://www.googleapis.com/auth/fitness.blood_pressure.write
https://www.googleapis.com/auth/fitness.body.read
https://www.googleapis.com/auth/fitness.body.write
https://www.googleapis.com/auth/fitness.body_temperature.read
https://www.googleapis.com/auth/fitness.body_temperature.write
https://www.googleapis.com/auth/fitness.location.read
https://www.googleapis.com/auth/fitness.location.write
https://www.googleapis.com/auth/fitness.nutrition.read
https://www.googleapis.com/auth/fitness.nutrition.write
https://www.googleapis.com/auth/fitness.oxygen_saturation.read
https://www.googleapis.com/auth/fitness.oxygen_saturation.write
https://www.googleapis.com/auth/fitness.reproductive_health.read
https://www.googleapis.com/auth/fitness.reproductive_health.write
https://www.googleapis.com/auth/games
https://www.googleapis.com/auth/games.firstparty
https://www.googleapis.com/auth/games_lite
https://www.googleapis.com/auth/grants.audit
https://www.googleapis.com/auth/myphonenumbers
https://www.googleapis.com/auth/payments.make_payments
https://www.googleapis.com/auth/paymentssandbox.make_payments
https://www.googleapis.com/auth/plus.applications.manage
https://www.googleapis.com/auth/plus.circles.members
https://www.googleapis.com/auth/plus.circles.read
https://www.googleapis.com/auth/plus.circles.write
https://www.googleapis.com/auth/plus.login
https://www.googleapis.com/auth/plus.me
https://www.googleapis.com/auth/plus.media.upload
https://www.googleapis.com/auth/plus.pages.manage
https://www.googleapis.com/auth/plus.peopleapi.readwrite
https://www.googleapis.com/auth/plus.profiles.read
https://www.googleapis.com/auth/plus.profiles.write
https://www.googleapis.com/auth/plus.settings
https://www.googleapis.com/auth/plus.stream.read
https://www.googleapis.com/auth/plus.stream.write
https://www.googleapis.com/auth/pos
https://www.googleapis.com/auth/userinfo.email
https://www.googleapis.com/auth/userinfo.profile
https://www.googleapis.com/auth/youtube**

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
Permissions
android.permission.INTERNET
android.permission.WRITE_EXTERNAL_STORAGE
com.zgsbrgr.gearvr.injector.permission.C2D_MESSAGE
android.permission.ACCESS_NETWORK_STATE
android.permission.READ_EXTERNAL_STORAGE
android.permission.REQUEST_INSTALL_PACKAGES
android.permission.WAKE_LOCK
com.google.android.c2dm.permission.RECEIVE
com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE
Activities
com.zgsbrgr.gearvr.injector.MainActivity
com.zgsbrgr.gearvr.injector.AboutActivity
com.zgsbrgr.gearvr.injector.LinkInjectorActivity
com.zgsbrgr.gearvr.injector.UrlInjectorActivity
com.zgsbrgr.gearvr.injector.FileInjectorActivity
com.google.android.gms.appinvite.PreviewActivity
com.google.android.gms.common.api.GoogleApiActivity
com.google.android.gms.ads.AdActivity
Services
com.google.firebase.components.ComponentDiscoveryService
com.google.android.gms.measurement.AppMeasurementService
com.google.android.gms.measurement.AppMeasurementJobService
com.google.firebase.iid.FirebaseInstanceIdService
Receivers
com.google.android.gms.measurement.AppMeasurementReceiver
com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver
com.google.firebase.iid.FirebaseInstanceIdReceiver
Providers
com.zgsbrgr.gearvr.injector.GenericFileProvider
com.crashlytics.android.CrashlyticsInitProvider
com.google.firebase.provider.FirebaseInitProvider
Intent Filters By Action
com.google.android.gms.appinvite.ACTION_PREVIEW
android.intent.action.VIEW
android.intent.action.MAIN
com.google.firebase.INSTANCE_ID_EVENT
com.android.vending.INSTALL_REFERRER
com.google.android.c2dm.intent.RECEIVE
Intent Filters By Category
android.intent.category.DEFAULT
android.intent.category.BROWSABLE
android.intent.category.LAUNCHER
com.zgsbrgr.gearvr.injector

Contained Files By Type
PNG	291
XML	202
Unknown	41
GIF	3
DEX	2
ZIP	1
Contained Files By Extension
Png	291
Xml	201
Gif	3
Dex	2
Gz	1
RSA	1
Jks	1
Apk	1
SF	1
MF	1
Dtd	1

**Comment by DrBeef** [comment]
Closing, this isn't a QuakeGVR issue, though thanks for the warning

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
Apologies for the multiple posting of this issue, didn't mean to spam, never had someone with manual approvals on their issues before, not used to that. Since I cannot delete the others, I at least edited them.

I do appreciate your response, and I know that it has nothing to do with quake VR, but since you linked it in your readme, I figured the polite thing to do would be to inform you. Thanks for reading.

**Comment by DrBeef** [comment]
No problem, not sure I have manual approvals for issues turned on (I haven't turned it on myself), other people have posted issues without any trouble so not sure what's going on there. I wish there was an alternative to some dodgy looking injector app, but I'm not currently in a position to provide one myself. Thanks for raising awareness though, better people are informed of what they are installing on their devices.
